### ISSUE TITLE
Wrong placement of acceptor_principal setting

### ISSUE THREAD

**Issue by jochenkressin** [floragunncom/search-guard-auth-http-kerberos#2]
In our config templates, the key

acceptor_principal: ...

is in sg_config.yml, when in fact it needs to be configured in elasticsearch.yml.

I've updated the documentation, please correct the respective key also in our templates.

**Comment by floragunn** [comment]
needs to be configured in elasticsearch.yml, done with https://github.com/floragunncom/search-guard/commit/6e0f789c0338eb05ec3278ba3b2c87f3ff948178
